# Generated by Django 5.2.5 on 2025-08-16 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryCodeCleanUpScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField()),
                ('deleted_count', models.PositiveIntegerField(default=0)),
                ('enable_scheduler', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('s', 'Success'), ('f', 'Failure'), ('d', 'Deleted')], max_length=1)),
                ('error_message', models.TextField()),
            ],
            options={
                'ordering': ['-run_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryCodesBatch',
            fields=[
                ('id', models.UUIDField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('number_issued', models.PositiveBigIntegerField()),
                ('number_removed', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('a', 'Active'), ('i', 'Invalidate'), ('u', 'Used'), ('p', 'Pending Delete')], default='a', max_length=1)),
                ('automatic_removal', models.BooleanField(default=True)),
                ('expiry_date', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_batches', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('id', models.UUIDField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('mark_for_deletion', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('a', 'Active'), ('i', 'Invalidate'), ('u', 'Used'), ('p', 'Pending Delete')], default='a', max_length=1)),
                ('automatic_removal', models.BooleanField(default=True)),
                ('days_to_expiry', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to='django_2fa_recovery_codes.recoverycodesbatch')),
            ],
        ),
    ]
