# Generated by Django 5.2.5 on 2025-08-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_2fa_recovery_codes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoverycode',
            name='hash_code',
            field=models.CharField(db_index=True, default='sssssssssssssssssssssssssssssssssssssssss', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
