# Generated by Django 5.2.5 on 2025-08-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_2fa_recovery_codes', '0002_recoverycode_hash_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverycodesbatch',
            name='number_removed',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
