# Generated by Django 5.2.5 on 2025-08-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_2fa_recovery_codes', '0003_alter_recoverycodesbatch_number_removed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverycodesbatch',
            name='expiry_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
