# Generated by Django 5.2.5 on 2025-08-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_2fa_recovery_codes', '0004_alter_recoverycodesbatch_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverycodesbatch',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
