# Generated by Django 5.2.5 on 2025-08-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_2fa_recovery_codes', '0005_alter_recoverycodesbatch_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoverycode',
            name='code_downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recoverycode',
            name='code_emailed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recoverycodesbatch',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recoverycodesbatch',
            name='emailed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recoverycodesbatch',
            name='generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recoverycodesbatch',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
