# Generated by Django 5.2.5 on 2025-08-17 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_2fa_recovery_codes', '0006_recoverycode_code_downloaded_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recoverycode',
            old_name='days_to_expiry',
            new_name='days_to_expire',
        ),
    ]
