# Generated by Django 5.2.5 on 2025-08-17 02:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_2fa_recovery_codes', '0007_rename_days_to_expiry_recoverycode_days_to_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverycodesbatch',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
