# Generated by Django 5.2.5 on 2025-08-28 16:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryCodeCleanUpScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField()),
                ('deleted_count', models.PositiveIntegerField(default=0)),
                ('enable_scheduler', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('s', 'Success'), ('f', 'Failure'), ('d', 'Deleted')], max_length=1)),
                ('error_message', models.TextField()),
            ],
            options={
                'ordering': ['-run_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryCodeEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(db_index=True, max_length=100)),
                ('to_email', models.EmailField(db_index=True, max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('sent_on', models.DateTimeField(auto_now_add=True)),
                ('email_body', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecoveryCodesBatch',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('number_issued', models.PositiveSmallIntegerField(default=10)),
                ('number_removed', models.PositiveSmallIntegerField(default=0)),
                ('number_invalidated', models.PositiveSmallIntegerField(default=0)),
                ('number_used', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('a', 'Active'), ('i', 'Invalidate'), ('u', 'Used'), ('p', 'Pending Delete')], default='a', max_length=1)),
                ('automatic_removal', models.BooleanField(default=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('viewed', models.BooleanField(default=False)),
                ('downloaded', models.BooleanField(default=False)),
                ('emailed', models.BooleanField(default=False)),
                ('generated', models.BooleanField(default=False)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_batches', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('hash_code', models.CharField(db_index=True, editable=False, max_length=128)),
                ('look_up_hash', models.CharField(blank=True, db_index=True, editable=False, max_length=128, unique=True)),
                ('mark_for_deletion', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('a', 'Active'), ('i', 'Invalidate'), ('u', 'Used'), ('p', 'Pending Delete')], db_index=True, default='a', max_length=1)),
                ('automatic_removal', models.BooleanField(default=True)),
                ('days_to_expire', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('code_downloaded', models.BooleanField(default=False)),
                ('code_emailed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to='django_auth_recovery_codes.recoverycodesbatch')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'look_up_hash'], name='user_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'look_up_hash'), name='unique_user_lookup_hash')],
            },
        ),
    ]
