# Generated by Django 5.2.5 on 2025-08-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoverycode',
            name='is_deactived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recoverycode',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
