# Generated by Django 5.2.5 on 2025-08-29 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recoverycode',
            name='code_downloaded',
        ),
        migrations.RemoveField(
            model_name='recoverycode',
            name='code_emailed',
        ),
    ]
