# Generated by Django 5.2.5 on 2025-08-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryCodeEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(db_index=True, max_length=100)),
                ('to_email', models.EmailField(db_index=True, max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('sent_on', models.DateTimeField(auto_now_add=True)),
                ('email_body', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
