# Generated by Django 5.2.5 on 2025-08-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0002_recoverycodeemaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoverycodesbatch',
            name='number_invalidated',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recoverycodesbatch',
            name='number_issued',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='recoverycodesbatch',
            name='number_removed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
