# Generated by Django 5.2.5 on 2025-08-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0003_recoverycodesbatch_number_invalidated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoverycodesbatch',
            name='number_used',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
