# Generated by Django 5.2.5 on 2025-08-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0003_recoverycodeaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoverycodeaudit',
            name='number_deleted',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recoverycodeaudit',
            name='action',
            field=models.CharField(choices=[('deleted', 'Deleted'), ('invalidated', 'Invalidated'), ('already_deleted', 'Already deleted'), ('already_invalidated', 'Already invalidated'), ('invalid_code', 'Invalid code entered'), ('batch_marked_for_deletion', 'Batch marked for deletion'), ('batch_purged', 'Batch purged (async deletion)')], max_length=50),
        ),
    ]
