# Generated by Django 5.2.5 on 2025-08-30 20:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0004_recoverycodeaudit_number_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryCodePurgeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_codes_purged', models.PositiveIntegerField(default=0)),
                ('total_batches_purged', models.PositiveIntegerField(default=0)),
                ('retention_days', models.PositiveIntegerField(default=30)),
            ],
        ),
        migrations.AddField(
            model_name='recoverycodecleanupscheduler',
            name='bulk_delete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recoverycodecleanupscheduler',
            name='delete_empty_batch',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recoverycodecleanupscheduler',
            name='log_per_code',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recoverycodecleanupscheduler',
            name='name',
            field=models.CharField(default='Purge Expired Recovery codes', max_length=180),
        ),
        migrations.AddField(
            model_name='recoverycodecleanupscheduler',
            name='next_run',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recoverycodecleanupscheduler',
            name='retention_days',
            field=models.PositiveBigIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='recoverycodecleanupscheduler',
            name='schedule_type',
            field=models.CharField(choices=[('O', 'Once'), ('T', 'Minutes'), ('H', 'Hourly'), ('D', 'Daily'), ('W', 'Weekly'), ('Q', 'Quarterly'), ('Y', 'Yearly')], default='D', max_length=1),
        ),
    ]
