# Generated by Django 5.2.5 on 2025-08-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0005_recoverycodepurgehistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverycodecleanupscheduler',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recoverycodecleanupscheduler',
            name='status',
            field=models.CharField(choices=[('s', 'Success'), ('f', 'Failure'), ('d', 'Deleted'), ('p', 'Pending')], default='p', max_length=1),
        ),
    ]
