# Generated by Django 5.2.5 on 2025-08-30 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0006_alter_recoverycodecleanupscheduler_error_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='recoverycodeaudit',
            old_name='timestamped',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='recoverycodeaudit',
            name='modified_at',
        ),
        migrations.AddField(
            model_name='recoverycodeaudit',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recoverycodeaudit',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='django_auth_recovery_codes.recoverycodesbatch'),
        ),
        migrations.AlterField(
            model_name='recoverycodeaudit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_code_audits', to=settings.AUTH_USER_MODEL),
        ),
    ]
