# Generated by Django 5.2.5 on 2025-08-31 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0007_rename_timestamped_recoverycodeaudit_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoverycodepurgehistory',
            name='name',
            field=models.CharField(default='Recovery code purged history log', max_length=128),
        ),
    ]
