# Generated by Django 5.2.5 on 2025-08-31 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0009_alter_recoverycodepurgehistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverycodepurgehistory',
            name='name',
            field=models.CharField(default='Recovery code purged history log', max_length=128),
        ),
    ]
