# Generated by Django 5.2.5 on 2025-08-31 02:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0010_alter_recoverycodepurgehistory_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recoverycodeaudit',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='recoverycodeaudit',
            old_name='deleted_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='recoverycodeaudit',
            old_name='user',
            new_name='user_issued_to',
        ),
        migrations.AddField(
            model_name='recoverycodeaudit',
            name='number_issued',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recoverycodeaudit',
            name='number_deleted',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='recoverycodeaudit',
            index=models.Index(fields=['-timestamp'], name='recoverycodeaudit_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='recoverycodeaudit',
            index=models.Index(fields=['action'], name='recoverycodeaudit_action_idx'),
        ),
        migrations.AddIndex(
            model_name='recoverycodeaudit',
            index=models.Index(fields=['user_issued_to'], name='recoverycodeaudit_user_idx'),
        ),
        migrations.AddIndex(
            model_name='recoverycodeaudit',
            index=models.Index(fields=['batch'], name='recoverycodeaudit_batch_idx'),
        ),
    ]
