# Generated by Django 5.2.5 on 2025-08-31 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0011_alter_recoverycodeaudit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoverycodecleanupscheduler',
            name='minutes_interval',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recoverycodecleanupscheduler',
            name='schedule_type',
            field=models.CharField(choices=[('O', 'Once'), ('H', 'Hourly'), ('I', 'Interval'), ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('Y', 'Yearly')], default='D', max_length=1),
        ),
    ]
