# Generated by Django 5.2.5 on 2025-08-31 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0012_recoverycodecleanupscheduler_minutes_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverycodecleanupscheduler',
            name='minutes_interval',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
