# Generated by Django 5.2.5 on 2025-08-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0013_alter_recoverycodecleanupscheduler_minutes_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverycodecleanupscheduler',
            name='minutes_interval',
            field=models.PositiveSmallIntegerField(blank=True, default=True),
            preserve_default=False,
        ),
    ]
