# Generated by Django 5.2.5 on 2025-08-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0014_alter_recoverycodecleanupscheduler_minutes_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recoverycodecleanupscheduler',
            name='minutes_interval',
        ),
        migrations.AlterField(
            model_name='recoverycodecleanupscheduler',
            name='schedule_type',
            field=models.CharField(choices=[('O', 'Once'), ('H', 'Hourly'), ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('Y', 'Yearly')], default='D', max_length=1),
        ),
    ]
