# Generated by Django 5.2.5 on 2025-08-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0015_remove_recoverycodecleanupscheduler_minutes_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverycodecleanupscheduler',
            name='next_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
