# Generated by Django 5.2.5 on 2025-08-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0016_alter_recoverycodecleanupscheduler_next_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryCodeAuditScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('enable_scheduler', models.BooleanField(default=True)),
                ('retention_days', models.PositiveBigIntegerField(default=30)),
                ('run_at', models.DateTimeField()),
                ('schedule_type', models.CharField(choices=[('O', 'Once'), ('H', 'Hourly'), ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('Y', 'Yearly')], default='D', help_text='Select how often this task should run.', max_length=1)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('deleted_count', models.PositiveIntegerField(default=0, editable=False)),
                ('status', models.CharField(choices=[('s', 'Success'), ('f', 'Failure'), ('d', 'Deleted'), ('p', 'Pending')], default='p', editable=False, max_length=1)),
                ('error_message', models.TextField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['-run_at'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='recoverycodecleanupscheduler',
            name='schedule_type',
            field=models.CharField(choices=[('O', 'Once'), ('H', 'Hourly'), ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('Y', 'Yearly')], default='D', help_text='Select how often this task should run.', max_length=1),
        ),
    ]
