# Generated by Django 5.2.5 on 2025-08-31 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0017_recoverycodeauditscheduler_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverycodeauditscheduler',
            name='name',
            field=models.CharField(default='Clean up recovery codes audit', max_length=180),
        ),
    ]
