# Generated by Django 5.2.5 on 2025-09-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0019_alter_recoverycodeauditscheduler_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoverycodeaudit',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recoverycodeauditscheduler',
            name='name',
            field=models.CharField(default='Remove Recovery code audit_13fbd3daf596429a87', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='recoverycodecleanupscheduler',
            name='name',
            field=models.CharField(default='Purge Expired Recovery Codes_cc34c6b156a2468ea3', max_length=180, unique=True),
        ),
    ]
