# Generated by Django 5.2.5 on 2025-09-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0020_recoverycodeaudit_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recoverycodeaudit',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='recoverycodeauditscheduler',
            name='name',
            field=models.CharField(default='Remove Recovery code audit_3d89054472b14962ac', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='recoverycodecleanupscheduler',
            name='name',
            field=models.CharField(default='Purge Expired Recovery Codes_395e0c94680340e089', max_length=180, unique=True),
        ),
    ]
