# Generated by Django 5.2.5 on 2025-09-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0021_remove_recoverycodeaudit_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverycodeauditscheduler',
            name='name',
            field=models.CharField(default='Remove Recovery code audit_b4f005eb19e64d0981', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='recoverycodecleanupscheduler',
            name='name',
            field=models.CharField(default='Purge Expired Recovery Codes_3d938173e4314340a4', max_length=180, unique=True),
        ),
    ]
