# Generated by Django 5.2.5 on 2025-09-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0024_alter_recoverycodeauditscheduler_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoverycodecleanupscheduler',
            name='use_with_logger',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='recoverycodeauditscheduler',
            name='name',
            field=models.CharField(default='Remove Recovery code audit_5fa3dd03075c4a6b8b', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='recoverycodecleanupscheduler',
            name='name',
            field=models.CharField(default='Purge Expired Recovery Codes_e10bdef6f6784194bd', max_length=180, unique=True),
        ),
    ]
