# Generated by Django 5.2.5 on 2025-09-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0026_alter_recoverycodeauditscheduler_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoverycodeauditscheduler',
            name='use_with_logger',
            field=models.BooleanField(default=False, editable=False, help_text="Set in the setting using the flag 'DJANGO_AUTH_RECOVERY_CODE_PURGE_DELETE_SCHEDULER_USE_LOGGER' "),
        ),
        migrations.AlterField(
            model_name='recoverycodeauditscheduler',
            name='name',
            field=models.CharField(default='Remove Recovery code audit_e1cc2577932549f9b1', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='recoverycodecleanupscheduler',
            name='name',
            field=models.CharField(default='Purge Expired Recovery Codes_2c06eb2e747f48f0b7', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='recoverycodecleanupscheduler',
            name='use_with_logger',
            field=models.BooleanField(default=False, editable=False, help_text="Set in the setting using the flag 'DJANGO_AUTH_RECOVERY_CODE_PURGE_DELETE_SCHEDULER_USE_LOGGER' "),
        ),
    ]
