# Generated by Django 5.2.5 on 2025-09-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0029_alter_recoverycodeauditscheduler_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverycodeauditscheduler',
            name='deleted_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recoverycodeauditscheduler',
            name='name',
            field=models.CharField(default='Remove Recovery code audit_209e2024248e436fa1', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='recoverycodeauditscheduler',
            name='status',
            field=models.CharField(choices=[('s', 'Success'), ('f', 'Failure'), ('d', 'Deleted'), ('p', 'Pending')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='recoverycodeauditscheduler',
            name='use_with_logger',
            field=models.BooleanField(default=False, help_text="Set in the setting using the flag 'DJANGO_AUTH_RECOVERY_CODE_PURGE_DELETE_SCHEDULER_USE_LOGGER' "),
        ),
        migrations.AlterField(
            model_name='recoverycodecleanupscheduler',
            name='name',
            field=models.CharField(default='Purge Expired Recovery Codes_df3cc3ecfbf84d9ea7', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='recoverycodecleanupscheduler',
            name='status',
            field=models.CharField(choices=[('s', 'Success'), ('f', 'Failure'), ('d', 'Deleted'), ('p', 'Pending')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='recoverycodecleanupscheduler',
            name='use_with_logger',
            field=models.BooleanField(default=False, help_text="Set in the setting using the flag 'DJANGO_AUTH_RECOVERY_CODE_PURGE_DELETE_SCHEDULER_USE_LOGGER' "),
        ),
    ]
