# Generated by Django 5.2.5 on 2025-09-05 05:19

import django_auth_recovery_codes.base_models
from django_auth_recovery_codes.app_settings import default_multiplier, default_cooldown_seconds
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0030_alter_recoverycodeauditscheduler_deleted_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoverycodesbatch',
            name='cooldown_minutes',
            field=models.PositiveSmallIntegerField(default=default_cooldown_seconds),
        ),
        migrations.AddField(
            model_name='recoverycodesbatch',
            name='last_generated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recoverycodesbatch',
            name='requested_attempt',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recoverycodeauditscheduler',
            name='name',
            field=models.CharField(default='Remove Recovery code audit_2e648cd7474b49b7ba', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='recoverycodeauditscheduler',
            name='use_with_logger',
            field=models.BooleanField(default=django_auth_recovery_codes.base_models.get_default_logger, help_text="If True, the scheduler will use a logger to record the sending of emails. Default value comes from the setting 'DJANGO_AUTH_RECOVERY_CODE_PURGE_DELETE_SCHEDULER_USE_LOGGER'."),
        ),
        migrations.AlterField(
            model_name='recoverycodecleanupscheduler',
            name='name',
            field=models.CharField(default='Purge Expired Recovery Codes_a2b8f162987b417786', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='recoverycodecleanupscheduler',
            name='use_with_logger',
            field=models.BooleanField(default=django_auth_recovery_codes.base_models.get_default_logger, help_text="If True, the scheduler will use a logger to record the sending of emails. Default value comes from the setting 'DJANGO_AUTH_RECOVERY_CODE_PURGE_DELETE_SCHEDULER_USE_LOGGER'."),
        ),
    ]
