# Generated by Django 5.2.5 on 2025-09-05 16:53

import django_auth_recovery_codes.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0031_recoverycodesbatch_cooldown_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoverycodesbatch',
            name='multiplier',
            field=models.PositiveSmallIntegerField(default=django_auth_recovery_codes.utils.utils.default_multiplier, help_text='The multiplier used to increase the wait time .Default value used from the settings.DJANGO_AUTH_RECOVERY_CODES_COOLDOWN_MULTIPLIER'),
        ),
        migrations.AlterField(
            model_name='recoverycodeauditscheduler',
            name='name',
            field=models.CharField(default='Remove Recovery code audit_a4b95658ec6e46eb82', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='recoverycodecleanupscheduler',
            name='name',
            field=models.CharField(default='Purge Expired Recovery Codes_993a1cc4e6454feb9f', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='recoverycodesbatch',
            name='cooldown_minutes',
            field=models.PositiveSmallIntegerField(default=django_auth_recovery_codes.utils.utils.default_cooldown_minutes, help_text='The number of minutes in seconds before a new request can be made. Defaultvalued used from the settings.DJANGO_AUTH_RECOVERY_CODES_BASE_COOLDOWN'),
        ),
    ]
