# Generated by Django 5.2.5 on 2025-09-07 17:14


from django.db import migrations, models
from django_auth_recovery_codes.app_settings import default_multiplier, default_cooldown_seconds

class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0032_recoverycodesbatch_multiplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recoverycodesbatch',
            name='cooldown_minutes',
        ),
        migrations.AddField(
            model_name='recoverycodesbatch',
            name='cooldown_seconds',
            field=models.PositiveSmallIntegerField(default=default_cooldown_seconds, help_text='The number of seconds before a new request can be made. Default valued used from the settings.DJANGO_AUTH_RECOVERY_CODES_BASE_COOLDOWN flag'),
        ),
        migrations.AlterField(
            model_name='recoverycodeauditscheduler',
            name='name',
            field=models.CharField(default='Remove Recovery code audit_9f3b138f15b24db9b4', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='recoverycodecleanupscheduler',
            name='name',
            field=models.CharField(default='Purge Expired Recovery Codes_f1f825574cfc41f5bb', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='recoverycodesbatch',
            name='multiplier',
            field=models.PositiveSmallIntegerField(default=default_multiplier, help_text='The multiplier used to increase the wait time .Default value used from the settings.DJANGO_AUTH_RECOVERY_CODES_COOLDOWN_MULTIPLIER flag'),
        ),
    ]
