# Generated by Django 5.2.5 on 2025-09-10 00:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0036_alter_recoverycodeauditscheduler_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoverycodesetup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recoverycodesetup',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recoverycodeauditscheduler',
            name='name',
            field=models.CharField(default='Remove Recovery code audit_cb1b0dde539b44f5a5', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='recoverycodecleanupscheduler',
            name='name',
            field=models.CharField(default='Purge Expired Recovery Codes_14b57a2806944bb0a1', max_length=180, unique=True),
        ),
    ]
