# Generated by Django 5.2.5 on 2025-09-20 14:22

import django.db.models.deletion
import django_auth_recovery_codes.app_settings
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0037_recoverycodesetup_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='recoverycodesbatch',
            old_name='last_generated',
            new_name='last_attempt',
        ),
        migrations.AlterField(
            model_name='recoverycode',
            name='status',
            field=models.CharField(choices=[('a', 'Active'), ('i', 'Invalidate'), ('p', 'Pending Delete')], db_index=True, default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='recoverycodeauditscheduler',
            name='name',
            field=models.CharField(default='Remove Recovery code audit_dbdc79ad23fb4b179d', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='recoverycodecleanupscheduler',
            name='name',
            field=models.CharField(default='Purge Expired Recovery Codes_0bbd960b718a48eda2', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='recoverycodesbatch',
            name='status',
            field=models.CharField(choices=[('a', 'Active'), ('i', 'Invalidate'), ('p', 'Pending Delete')], default='a', max_length=1),
        ),
        migrations.CreateModel(
            name='LoginRateLimiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('cooldown_seconds', models.PositiveSmallIntegerField(default=django_auth_recovery_codes.app_settings.default_cooldown_seconds, help_text='The number of seconds before a new request can be made. Default valued used from the settings.DJANGO_AUTH_RECOVERY_CODES_BASE_COOLDOWN flag')),
                ('multiplier', models.PositiveSmallIntegerField(default=django_auth_recovery_codes.app_settings.default_multiplier, help_text='The multiplier used to increase the wait time .Default value used from the settings.DJANGO_AUTH_RECOVERY_CODES_COOLDOWN_MULTIPLIER flag')),
                ('login_attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_login_attempts', models.PositiveSmallIntegerField(default=django_auth_recovery_codes.app_settings.default_max_login_attempts)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('last_login_attempt', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
