# Generated by Django 5.2.5 on 2025-09-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0040_alter_recoverycodeauditscheduler_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recoverycodecleanupscheduler',
            name='log_per_code',
        ),
        migrations.AlterField(
            model_name='recoverycodeauditscheduler',
            name='name',
            field=models.CharField(default='Remove Recovery code audit_e56ddee60f6f487c82', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='recoverycodecleanupscheduler',
            name='name',
            field=models.CharField(default='Purge Expired Recovery Codes_7f67dad3ba444899a6', max_length=180, unique=True),
        ),
    ]
