# Generated by Django 5.2.5 on 2025-09-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0041_remove_recoverycodecleanupscheduler_log_per_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverycodeauditscheduler',
            name='name',
            field=models.CharField(default='Remove Recovery code audit_f3f7ff23151c415584', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='recoverycodecleanupscheduler',
            name='name',
            field=models.CharField(default='Purge Expired Recovery Codes_f197fba2b9874165a6', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='recoverycodesbatch',
            name='expiry_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='recoverycodesbatch',
            name='status',
            field=models.CharField(choices=[('a', 'Active'), ('i', 'Invalidate'), ('p', 'Pending Delete')], db_index=True, default='a', max_length=1),
        ),
    ]
