# Generated by Django 5.2.7 on 2025-10-04 18:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0042_alter_recoverycodeauditscheduler_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverycodeauditscheduler',
            name='name',
            field=models.CharField(default='Remove Recovery code audit_239431e1de394d65a1', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='recoverycodecleanupscheduler',
            name='name',
            field=models.CharField(default='Purge Expired Recovery Codes_89c360ea2af34ed789', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='recoverycodesbatch',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RecoveryCodesBatchHistory',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('number_issued', models.PositiveSmallIntegerField(default=10)),
                ('number_removed', models.PositiveSmallIntegerField(default=0)),
                ('number_invalidated', models.PositiveSmallIntegerField(default=0)),
                ('number_used', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('a', 'Active'), ('i', 'Invalidate'), ('p', 'Pending Delete')], db_index=True, default='a', max_length=1)),
                ('expiry_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('viewed', models.BooleanField(default=False)),
                ('downloaded', models.BooleanField(default=False)),
                ('emailed', models.BooleanField(default=False)),
                ('generated', models.BooleanField(default=False)),
                ('batch_id', models.UUIDField()),
                ('deleted_by_username', models.CharField(blank=True, max_length=60)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_batches_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recovery Code Batch History',
                'verbose_name_plural': 'Recovery Code Batch Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
