# Generated by Django 5.2.6 on 2025-10-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0043_alter_recoverycodeauditscheduler_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recoverycodenotification',
            old_name='modifed_at',
            new_name='modified_at',
        ),
        migrations.AlterField(
            model_name='recoverycodeauditscheduler',
            name='name',
            field=models.CharField(default='Remove Recovery code audit_31cc030acb3a457f83', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='recoverycodecleanupscheduler',
            name='name',
            field=models.CharField(default='Purge Expired Recovery Codes_84b297df770b4730a7', max_length=180, unique=True),
        ),
    ]
