# Generated by Django 5.2.7 on 2025-10-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0043_alter_recoverycodeauditscheduler_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverycodeauditscheduler',
            name='name',
            field=models.CharField(default='Remove Recovery code audit_9be6fd369abb4251a8', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='recoverycodecleanupscheduler',
            name='name',
            field=models.CharField(default='Purge Expired Recovery Codes_0d0b4c933e7740b88b', max_length=180, unique=True),
        ),
    ]
