# Generated by Django 5.2.5 on 2025-10-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0044_rename_modifed_at_recoverycodenotification_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverycodeauditscheduler',
            name='name',
            field=models.CharField(default='Remove Recovery code audit_b69e8735394f4654bd', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='recoverycodecleanupscheduler',
            name='name',
            field=models.CharField(default='Purge Expired Recovery Codes_2f716c445bdb4a3582', max_length=180, unique=True),
        ),
    ]
