# Generated by Django 5.2.5 on 2025-10-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0045_alter_recoverycodeauditscheduler_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverycodeauditscheduler',
            name='name',
            field=models.CharField(default='Remove Recovery code audit_16c19156248f428985', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='recoverycodecleanupscheduler',
            name='name',
            field=models.CharField(default='Purge Expired Recovery Codes_bc258f32bd364f4ea2', max_length=180, unique=True),
        ),
    ]
