# Generated by Django 5.2.5 on 2025-10-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0046_alter_recoverycodeauditscheduler_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverycodeauditscheduler',
            name='name',
            field=models.CharField(default='Remove Recovery code audit_3d5398cd2c3848e593', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='recoverycodecleanupscheduler',
            name='name',
            field=models.CharField(default='Purge Expired Recovery Codes_fc2a2b86db9143d799', max_length=180, unique=True),
        ),
    ]
