# Generated by Django 5.2.7 on 2025-10-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0046_alter_recoverycodeauditscheduler_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverycodeauditscheduler',
            name='name',
            field=models.CharField(default='Remove Recovery code audit_ca2857de6067413aa8', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='recoverycodecleanupscheduler',
            name='name',
            field=models.CharField(default='Purge Expired Recovery Codes_2756db5bd8bb4ce287', max_length=180, unique=True),
        ),
    ]
