# Generated by Django 5.2.7 on 2025-10-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0048_alter_recoverycodeauditscheduler_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoverycodesbatch',
            name='temporary_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recoverycodeauditscheduler',
            name='name',
            field=models.CharField(default='Remove Recovery code audit_f322bcdbc33e49159b', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='recoverycodecleanupscheduler',
            name='name',
            field=models.CharField(default='Purge Expired Recovery Codes_e3d13a500664442fb8', max_length=180, unique=True),
        ),
    ]
