# Generated by Django 5.2.7 on 2025-10-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0049_recoverycodesbatch_temporary_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recoverycodesbatch',
            name='temporary_field',
        ),
        migrations.AlterField(
            model_name='recoverycodeauditscheduler',
            name='name',
            field=models.CharField(default='Remove Recovery code audit_63398fa41ba5420e84', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='recoverycodecleanupscheduler',
            name='name',
            field=models.CharField(default='Purge Expired Recovery Codes_a992cc6ac0ab43bb93', max_length=180, unique=True),
        ),
    ]
