# Generated by Django 5.2.7 on 2025-10-04 19:23
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings
import uuid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0051_alter_recoverycodeauditscheduler_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryCodesBatchHistory',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, unique=True, db_index=True)),
                ('batch_id', models.UUIDField()),
                ('number_issued', models.PositiveSmallIntegerField(default=10)),
                ('number_removed', models.PositiveSmallIntegerField(default=0)),
                ('number_invalidated', models.PositiveSmallIntegerField(default=0)),
                ('number_used', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=1, default='C', choices=[('C', 'CREATE'), ('U', 'UPDATE'), ('D', 'DELETE')], db_index=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True, db_index=True)),
                ('deleted_at', models.DateTimeField(null=True, blank=True)),
                ('deleted_by_username', models.CharField(max_length=60, blank=True)),
                ('viewed', models.BooleanField(default=False)),
                ('downloaded', models.BooleanField(default=False)),
                ('emailed', models.BooleanField(default=False)),
                ('generated', models.BooleanField(default=False)),
                ('deleted_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL)),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_batches_history', blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Recovery Code Batch History',
                'verbose_name_plural': 'Recovery Code Batch Histories',
            },
        ),
    ]