# Generated by Django 5.2.7 on 2025-10-05 18:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_recovery_codes', '0052_create_recoverycodesbatchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverycode',
            name='status',
            field=models.CharField(choices=[('a', 'Active'), ('i', 'Invalidate'), ('p', 'Pending Delete'), ('d', 'Deleted')], db_index=True, default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='recoverycodeauditscheduler',
            name='name',
            field=models.CharField(default='Remove Recovery code audit_df05d5f6bf15459fa9', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='recoverycodecleanupscheduler',
            name='name',
            field=models.CharField(default='Purge Expired Recovery Codes_3755050b6dd046fc96', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='recoverycodesbatch',
            name='expiry_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='recoverycodesbatch',
            name='status',
            field=models.CharField(choices=[('a', 'Active'), ('i', 'Invalidate'), ('p', 'Pending Delete'), ('d', 'Deleted')], db_index=True, default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='recoverycodesbatchhistory',
            name='expiry_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='recoverycodesbatchhistory',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='recoverycodesbatchhistory',
            name='status',
            field=models.CharField(choices=[('a', 'Active'), ('i', 'Invalidate'), ('p', 'Pending Delete'), ('d', 'Deleted')], db_index=True, default='a', max_length=1),
        ),
    ]
